### ISSUE TITLE
Support addConfigured (example: LoadResource and <url>)

### ISSUE THREAD

**Issue by abreslav** [dmekhanikov/KAnt#22]

**Comment by dmekhanikov** [comment]
It's unclear how to make generator understand that LoadResource should support "url" nested element.
The connection between them is as follows: LoadResource has method addConfigured(ResourceCollection) and URLResource (aka url) implements ResourceCollection.

**Comment by dmekhanikov** [comment]
Possible solution:
We generate an empty trait ResourceCollectionContainer, and LoadResource DSL class implements it. Also it is an extension function ResourceCollectionContainder.url(...). We should generate such functions  and traits for every implemented interface.
